name: mavenwebapp
services:
  mavenwebapp:
    image: vkrishna8/maven-web-app:${IMAGE_TAG}
    ports:
    - 7070:8080
    networks:
    - mavenwebappbridge
networks:
  mavenwebappbridge:
    driver: bridge
