apiVersion: v1
kind: ReplicationController
metadata:
  name: maven-rc
spec:
  replicas: 1
  selector:
    app: maven
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
      - image: amruth0005/maven-web-application
        name: maven
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: maven-service
spec:
  selector:
    app: maven
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30001





