apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenweb-deployment
  namespace: test-namespace
spec:
  revisionHistoryLimit: 4
  replicas: 2
  minReadySeconds: 20
  selector:
    matchLabels:
      app: maven-label
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 2
  template:
    metadata:
      name: maven-pod
      labels:
        app: maven-label
    spec:
      containers:
      - name: mavenwebappcontainer
        image: sumandockeraccount/maven-web-application:IMAGE_TAG
        ports:
        - containerPort: 8080
        resources: 
          requests: 
            cpu: 250m 
            memory: 250Mi 
          limits: 
            cpu: 400m 
            memory: 500Mi


---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
  namespace: test-namespace
spec:
  type: NodePort
  selector:
    app: maven-label
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30005

