name: Ci with gradlew

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:

     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v2
       name: setup jdk 11
     - uses: actions/setup-java@v2
       with:
         java-version: '11'
         distribution: adopt
         cache: gradlew
     - name: grant the permisision of gradlew
       run: chmod +x gradlew
     - name: build with gradlew
       run: ./ gradlew build
