on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
    
jobs:
  sonarqube:
  runs-on: ubuntu-latest
  steps:
  
  - name: SonarQube Scan
    uses: sonarsource/sonarqube-scan-action@master
    env:
      SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST_URL }}

    # Check the Quality Gate status.
  - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      # Force to fail step after specific time.
      timeout-minutes: 5
      env:
      SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
